name: Check

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry config virtualenvs.create false
          make install
      - name: check-format
        run: |
          make format.check
      - name: lint
        run: |
          make lint
